name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Code style and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run all tests
        run: npm run test

  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          # file types to ignore
          skip: "*.json,*.yml,DIRECTORY.md"
          ignore_words_list: "ba,esy,yse,falsy"
